# configure updates globally
update: insecure

# configure dependency pinning globally
pin: True

# set the default branch
branch: master

# update schedule
schedule: "every day"

# search for requirement files
search: True

# configure the branch prefix the bot is using
# default: pyup-
branch_prefix: pyup/

# set a global prefix for PRs
pr_prefix: "PYUP #12345"

# allow to close stale PRs
close_prs: True